name: flutter_application_api
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/thermometer.png
    - images/barometer.png
    - images/cloudy.png
    - images/humidity.png
